### Create new user Ada
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "ada@ada.com",
  "name": "Ada L",
  "password": "salainen"
}

### Login with Ada
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "ada@ada.com",
  "password": "salainen"
}

### Create post with Ada
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYUBhZGEuY29tIiwiaWQiOjEsImlhdCI6MTY1MTY0OTQ1MH0.mYUJpL4Vmqi2BNa-F6lTi7uu6XON46-QAs6HqbZnva4

{
  "title": "The first blog added",
  "author": "Bob Blogger",
  "url": "google.com",
  "year": 2020
}

### Another blog with Ada
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYUBhZGEuY29tIiwiaWQiOjEsImlhdCI6MTY1MTY0OTQ1MH0.mYUJpL4Vmqi2BNa-F6lTi7uu6XON46-QAs6HqbZnva4

{
  "title": "The second blog",
  "author": "Bob the Blogger",
  "url": "google.com",
  "year": 2010
}

